### ISSUE TITLE
Teams aren't modified according to definition

### ISSUE THREAD

**Issue by itrich** [opentelekomcloud/ansible-collection-gitcontrol#34]
We're using this Ansible collection to maintain our organization on GitHub, see <https://scs.community/tech/2022/08/16/github-manager/>. Our configuration can be found at <https://github.com/SovereignCloudStack/github-manager>.

Managing members and repositories works great so far. However, teams aren't modified at all:
- members aren't added to their corresponding teams
- description isn't updated
- privacy has not changed

You can find our team definition here: https://github.com/SovereignCloudStack/github-manager/blob/main/orgs/SovereignCloudStack/teams/members.yml

The Ansible playbooks run fine without any errors: <https://github.com/SovereignCloudStack/github-manager/runs/7877530158?check_suite_focus=true>

Did we miss something? Why aren't the teams modified just as members and repositories?

**Comment by gtema** [comment]
Hey,

good to hear it works on most areas. For us team management is working so I would assume something is wrong on your side. What may be happening is that we moved all development to github_XX_XX modules and are not really maintaining teams/repo/members modules anymore. If you use those please consider switching.

We use it in the following way now:
- https://github.com/opentelekomcloud-infra/gitstyring/ is storing configuration and zuul jobs invocation
- https://github.com/opentelekomcloud-infra/otc-zuul-jobs/blob/master/zuul.d/gitcontrol-jobs.yaml are the job definitions (will not suit you by default, but may give you hints)
- https://github.com/opentelekomcloud-infra/otc-zuul-jobs/blob/master/roles/gitcontrol/tasks/main.yaml is the entry point of the apply job as such which expects to know only gitcontrol_root_dir and api_token. It of course expectes that gitcontrol_root_dir is available for the job if you invoke it with Zuul

BTW, I am now working on adding gitea API support which leads to small changes in the job definitions, but is not affecting github_xx_xx modules

**Comment by gtema** [comment]
Due to privacy considerations we were forced to move our teams and members definitions to the closed project, but it still looks same

gitcontrol/orgs/ORG_NAME/data.yaml

```
---
exclusive: true
members:
  - login: abc
    name: abc
  - login: superuser
    name: I am admin
    role: "admin"
...
teams:
  - slug: admin
    description: Team of infra admins
    members:
      - superuser
  - slug: test_group
    description: abc
    maintainers:
    members:
      - abc
      - superuser
...

```

I can not guarantee now privacy is changing really (but it should), but members are definitely added and removed properly

**Comment by tibeer** [comment]
@gtema this can be closed. we figured it out. It was a combination of the old modules and new parameters. For others that run into a similar issue: a playbook can look like this:

```yaml
---
- hosts: localhost

  vars:
    gitcontrol_root_dir: ./orgs
    organization: foobar
    git_type: github

  tasks:
    - name: Check {{ organization }} general data file
      ansible.builtin.stat:
        path: "{{ (gitcontrol_root_dir + '/' + organization + '/data.yaml') }}"
      register: org_data

    - name: Read {{ organization }} organization target data
      include_vars:
        file: "{{ org_data.stat.path }}"
        name: "org"
      when: org_data.stat.exists

    - name: Apply {{ organization }} members
      opentelekomcloud.gitcontrol.github_org_members:
        token: "{{ api_token }}"
        organization: "{{ organization }}"
        members: "{{ org.members }}"
      when:
        - "org is defined"
        - "org.members is defined"
        - "git_type == 'github'"
        - "api_token is defined"
      register: members

    - name: Apply {{ organization }} teams
      opentelekomcloud.gitcontrol.github_org_teams:
        token: "{{ api_token }}"
        organization: "{{ organization }}"
        teams: "{{ org.teams | default([]) }}"
      when:
        - "org is defined"
        - "org.teams is defined"
        - "git_type == 'github'"
        - "api_token is defined"
      register: teams

    - name: Find {{ organization }} repositories data
      ansible.builtin.find:
        paths: "{{ gitcontrol_root_dir + '/' + organization + '/repositories' }}"
        patterns: "*.yaml,*.yml"
        file_type: "file"
      register: repository_data

    - include_tasks: "process_repository_file.yaml"
      vars:
        data: "{{ lookup('file', zj_repository_file.path) | from_yaml  }}"
        type: "{{ org.type | default('github') }}"
      loop: "{{ repository_data.files }}"
      loop_control:
        loop_var: "zj_repository_file"

```
