### ISSUE TITLE
Known Issues / Problems we encountered

### ISSUE THREAD

**Issue by PKehnel** [opentelekomcloud/ansible-collection-gitcontrol#6]
Hey just a short list of issues we encountered: 

1. Inviting people throws an error. 
2. Teams are always created as 'Secret', even when using visibility=visible
3. Git-Repos need to exists and be initialised. 
4. Teams are not added to repos.
5. Teams are created, but race condition. When creating a new team. In the first run we get an error but the team is created, in the second run members are added and everything runs smoothly. 

And once again thx for the repo and the work.

**Comment by gtema** [comment]
1) please more details, cause it work for us (except #4)
2) what do you mean by that? mean team visibility? or member visibility?
3) ack
4) it work for us (https://github.com/opentelekomcloud-infra/gitstyring/blob/main/orgs/opentelekomcloud-docs/repositories/elastic-load-balancing.yml#L18 as example)
5) maybe. So far we were not really trying to create new teams, only to manage members and their assignment to repos

**Comment by PKehnel** [comment]
2.

```
teams:
  eco:
    description: Ecosystem
    visibility: visible
    parent:
    maintainer:
      - gtema
```

The visible parameter is not working when you create a Team. They are always secret.

**Comment by PKehnel** [comment]
1. 
With: 
```
---
users:
  - name: "xyz zxy"
    login: "xyz-zxy"
    visibility: Public
    role: Member
```
Where the above person is an active github account. 

We get following error: 

`fatal: [localhost]: FAILED! => {"changed": false, "errors": ["Cannot fetch invitations: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/enterprise/3.0/rest/reference/orgs#list-pending-organization-invitations\"}"], "msg": "'NoneType' object is not iterable"}`

[docs link](https://docs.github.com/en/enterprise-server@3.0/rest/reference/orgs#check-organization-membership-for-a-user)

**Comment by PKehnel** [comment]
4. 
```
  teams:
    maintain:
      - cloud-de-team
    pull:
    push:
    admin:
      - cloud-de-team
      
```
     
Following config has no effect in our case. No idea why.
